version: '3.4'

services:
  -mysql-docker-container:
    container_name: mysql-db
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: shop_bd
      
    ports:
      - "3306:3306"
    volumes:
      - ./dados:/var/lib/mysql


